---
pagetitle: "Oskar Timo Thoms: Academic"
title: "Academic"
---

## Publications

### Articles

-   Valerie Percival, Oskar Timo Thoms, Ben Oppenheim, Dane Rowlands, Carolyn Chisadza, Sara Fewer, Gavin Yamey, and others. Final report of "The *Lancet* Commission on peaceful societies through health equity and gender equality." [*The Lancet*](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(23)01348-X/fulltext) (September 6, 2023).

-   Geoff Dancy & Oskar Timo Thoms. "Do Truth Commissions Really Improve Democracy?" [*Comparative Political Studies*](https://doi.org/10.1177/00104140211024305), Vol.55, No 4 (2022).

-   "Human Rights Change, Politics of Law and Order, and Targeting of Torture." [*Simons Working Papers in Security and Development no. 66/2018*](http://summit.sfu.ca/item/18289), School for International Studies, Simon Fraser University, Vancouver (November 2018). \[[PDF](files/SWP2018.pdf)\]

-   Oskar N.T. Thoms, James Ron & Roland Paris. "State-Level Effects of Transitional Justice: What Do We Know?" [*International Journal of Transitional Justice*](https://doi.org/10.1093/ijtj/ijq012), Vol.4, No. 3 (2010).

-   Oskar N.T. Thoms & James Ron. "Public health, Conflict and Human Rights: Toward a Collaborative Research Agenda." [*Conflict & Health*](https://doi.org/10.1186/1752-1505-1-11), Vol. 1, No. 11 (Nov 2007). \[[PDF](http://www.conflictandhealth.com/content/pdf/1752-1505-1-11.pdf)\]

-   Oskar N.T. Thoms & James Ron. "Do Human Rights Violations Cause Internal Conflict?" [*Human Rights Quarterly*](https://doi.org/10.1353/hrq.2007.0034), Vol. 29, No. 3 (August 2007).

-   Howard Ramos, James Ron & Oskar N.T. Thoms. "Shaping the Media's Human Rights Agenda, 1986-2000." [*Journal of Peace Research*](https://doi.org/10.1177/0022343307078943), Vol. 44, No. 4 (July 2007).

### Policy Reports

-   Oskar N.T. Thoms, James Ron & Roland Paris. "The Effects of Transitional Justice Mechanisms: A Summary of Empirical Research Findings and Implications for Analysts and Practitioners." Working Paper, Centre for International Policy Studies, University of Ottawa, April 2008. \[[executive summary](http://aix1.uottawa.ca/~rparis/CIPS_Transitional_Justice_April2008_ExecSummary.pdf)\]

-   Oskar N.T. Thoms & James Ron. "Public Health, Conflict and Human Rights: Towards a Collaborative Research Agenda." Ottawa: Department of Foreign Affairs and International Trade, March 26, 2007.

-   Oskar N.T. Thoms & James Ron. 2006. "Do Human Rights Violations Cause Internal Conflict?" Gatineau: Canadian International Development Agency, February 28, 2006.

### Op-Eds

-   James Ron & Oskar N.T. Thoms. "The Jury is still out on International Justice." [*Ottawa Citizen*](files/citizenoped.pdf), July 26th, 2008.

-   James Ron & Oskar N.T. Thoms. "Can Canada Help Curb Civil Wars?" [*The Toronto Star*](files/tstaroped.pdf), April 12th, 2006.

 

## Teaching

-   [Human Security: From Policy to Practice](/files/INAF5704_syllabus.pdf) (NPSIA, Carleton University, Winter 2020)

-   [Statistics for International Affairs](/files/INAF5016_syllabus.pdf) (NPSIA, Carleton University, Fall 2019)

-   [Transitional Justice](/files/TJ_syllabus.pdf) (SIS, Simon Fraser University, Spring 2019)
