---
pagetitle: "Oskar Timo Thoms: Consulting Services"
title: "Consulting Services"
---

 

Starting in 2024, I will be available again to provide the following consulting services:

-   Research and writing

-   Quantitative data analysis and visualization

-   Data science and statistical programming in R and Shiny (web-based data apps)

-   Building datasets and automated data collection (incl. webscraping)

-   Building data websites with Quarto

-   Teaching R workshops (incl. RStudio, Tidyverse, git/GitHub integration, Quarto)

 

I bring the following to my consulting work:

-   PhD (Princeton University) in political science, with focus on international relations, quantitative methods, and comparative politics

-   Research expertise in issues of human rights, justice, and public policy

-   First-class quantitative methods training

-   Extensive experience in data management and quantitative analysis

-   Meticulous attention to detail and best practices

-   Transparency and reproducibility of quantitative analyses

-   Development of methodological approaches to examine policy research questions

-   Fourteen years of experience coding extensively in the R statistical programming language

-   Taught MA-level and undergraduate statistics and served as a statistical consultant

-   Editing and technical document preparation in a wide variety of formats (incl. LaTeX and Quarto)

 

I have worked as a consultant on policy research projects funded by the Department of Foreign Affairs and International Trade, the Canadian International Development Agency (both now Global Affairs Canada), the International Development Research Centre, and the Swedish Institute for Global Health Transformation.

 

For inquiries and my CV, please [contact me](index.html).
