---
pagetitle: "Data Links"
title: "Data"
---

\  

#### Human Rights & Transitional Justice

* [Human Rights Measurement Initiative](https://humanrightsmeasurement.org)
* [Ill-Treatment and Torture (ITT) Data Project](http://faculty.ucmerced.edu/cconrad2/Academic/ITT_Data_Collection.html)
* [Fariss and Schnakenberg's latent human rights scores](http://humanrightsscores.org)
* [Political Terror Scale](http://www.politicalterrorscale.org)
* [Cingranelli and Richards' Human Rights Data](http://www.humanrightsdata.com)
* [Transitional Justice Research Collaborative](http://transitionaljusticedata.com)
* [Transitional Justice Database Project](http://www.tjdbproject.com)
* [Post-Conflict Justice (PCJ) and During-Conflict Justice (DCJ) datasets](http://www.justice-data.com)

#### International Relations

* [UN Status of Treaties database](http://treaties.un.org/Pages/ParticipationStatus.aspx?clang=_en)
* [International Environmental Agreements database](http://iea.uoregon.edu/page.php?file=home.htm&amp;query=static)
* [Correlates of War Project](http://www.correlatesofwar.org)
* [Union of International Associations](http://www.uia.org/)

#### Organized Violence

* [Uppsala Conflict Data Program](https://ucdp.uu.se/)

#### Political Institutions

* [Varieties of Democracy](https://www.v-dem.net/en/)
* [INSCR datasets](http://www.systemicpeace.org/inscrdata.html)
* [The Global State of Democracy Indices](http://www.idea.int/gsod-indices/#/indices/world-map)

#### Social, Economic and other

* [UN country codes](http://unstats.un.org/unsd/methods/m49/m49.htm)
* [UN demographic and social data](http://unstats.un.org/unsd/demographic/default.htm)
* [World Development Indicators](http://data.worldbank.org/data-catalog/world-development-indicators)
* [OECD data](http://www.oecd.org/dac/stats/idsonline)
