---
pagetitle: "Oskar Timo Thoms: Publications"
title: "Publications"
---

\  

#### Scholarly Articles

* Geoff Dancy & Oskar Timo Thoms. "Do Truth Commissions Really Improve Democracy?" Forthcoming in [*Comparative Political studies*](https://doi.org/10.1177/00104140211024305).

* Oskar N.T. Thoms, James Ron & Roland Paris. "State-Level Effects of Transitional Justice: What Do We Know?" [*International Journal of Transitional Justice*](https://doi.org/10.1093/ijtj/ijq012), Vol.4, No. 3 (2010).

* Oskar N.T. Thoms & James Ron. "Public health, Conflict and Human Rights: Toward a Collaborative Research Agenda." [*Conflict & Health*](https://doi.org/10.1186/1752-1505-1-11), Vol. 1, No. 11 (Nov 2007). [[PDF](http://www.conflictandhealth.com/content/pdf/1752-1505-1-11.pdf)]

* Oskar N.T. Thoms & James Ron. "Do Human Rights Violations Cause Internal Conflict?" [*Human Rights Quarterly*](https://doi.org/10.1353/hrq.2007.0034), Vol. 29, No. 3 (August 2007).

* Howard Ramos, James Ron & Oskar N.T. Thoms. "Shaping the Media's Human Rights Agenda, 1986-2000." [*Journal of Peace Research*](https://doi.org/10.1177/0022343307078943), Vol. 44, No. 4 (July 2007).

#### Working Papers

* "Police organizational structure and human rights change." Paper presented at the Canadian Political Science Association Annual Conference, Vancouver, June 6, 2019.

* "Human rights and the politics of law and order." Invited to revise & resubmit.

* "Human Rights Change, Politics of Law and Order, and Targeting of Torture." [*Simons Working Papers in Security and Development no. 66/2018*](http://summit.sfu.ca/item/18289), School for International Studies, Simon Fraser University, Vancouver (November 2018). [[PDF](files/SWP2018.pdf)]

#### Commissioned Policy Reports

* Oskar N.T. Thoms, James Ron & Roland Paris. "The Effects of Transitional Justice Mechanisms: A Summary of Empirical Research Findings and Implications for Analysts and Practitioners." Working Paper, Centre for International Policy Studies, University of Ottawa, April 2008. [[executive summary](http://aix1.uottawa.ca/~rparis/CIPS_Transitional_Justice_April2008_ExecSummary.pdf)]

* Oskar N.T. Thoms & James Ron. "Public Health, Conflict and Human Rights: Towards a Collaborative Research Agenda." Ottawa: Department of Foreign Affairs and International Trade, March 26, 2007.

* Oskar N.T. Thoms & James Ron. 2006. "Do Human Rights Violations Cause Internal Conflict?" Gatineau: Canadian International Development Agency, February 28, 2006.

#### Op-Eds

* James Ron & Oskar N.T. Thoms. "The Jury is still out on International Justice." *Ottawa Citizen*, July 26th, 2008. [[PDF](files/citizenoped.pdf)]

* James Ron & Oskar N.T. Thoms. "Can Canada Help Curb Civil Wars?" *The Toronto Star*, April 12th, 2006. [[PDF](files/tstaroped.pdf)]
